# MagicBricks Data Cleaning

<div style="background:#0F4C4A; color:#F5F1E8; padding:12px; border-radius:6px;">
<b>Goal:</b> Turn the raw scraped listings into clean, analysis ready data. Parse prices, extract BHK and locality, standardize text, handle missing values, and flag outliers.
</div>

**Input:** MagicBricks_NaviMumbai_raw.csv (1608 listings, 1 to 4 BHK)  
**Output:** MagicBricks_NaviMumbai_clean.csv

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv(r"C:\Users\Mitali Padave\Downloads\MagicBricks_NaviMumbai_raw.xls")
pd.set_option("display.max_columns", 30)
print("raw shape:", df.shape)
df.head()

raw shape: (1608, 10)

,title,price,area,bhk,bathroom,furnishing,floor,transaction,society,posted_by
0,"1 BHK Apartment for Sale in Jindal Air, Panvel...",₹45 Lac,Carpet Area334 sqft,NaN,Bathroom1,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,Builder: Jindal Builder
1,"3 BHK Apartment for Sale in Palm Amore, Seawoo...",₹4.30 Cr,Carpet Area1320 sqft,NaN,Bathroom3,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
2,"2 BHK Apartment for Sale in Mass insignia, Kha...",₹1.11 Cr,Carpet Area650 sqft,NaN,NaN,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
3,"3 BHK Apartment for Sale in Godrej Bayview, Va...",₹4.37 Cr,Carpet Area1187 sqft,NaN,Bathroom3,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN
4,"2 BHK Apartment for Sale in Sai Shell, Ulwe Na...",₹1.54 Cr,Carpet Area777 sqft,NaN,Bathroom2,FurnishingUnfurnished,NaN,TransactionNew Property,NaN,NaN

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        1608 non-null   str
 1   price        1608 non-null   str
 2   area         1608 non-null   str
 3   bhk          0 non-null      float64
 4   bathroom     1604 non-null   str
 5   furnishing   1601 non-null   str
 6   floor        1500 non-null   str
 7   transaction  1608 non-null   str
 8   society      0 non-null      float64
 9   posted_by    1518 non-null   str
dtypes: float64(2), str(8)
memory usage: 401.6 KB

In [4]:
df.isnull().sum()

title             0
price             0
area              0
bhk            1608
bathroom          4
furnishing        7
floor           108
transaction       0
society        1608
posted_by        90
dtype: int64

## 1. Remove duplicate listings

In [5]:
before = len(df)
df = df.drop_duplicates(subset=["title", "price", "area"]).reset_index(drop=True)
print(f"removed {before - len(df)} duplicates -> {len(df)} rows")

removed 0 duplicates -> 1608 rows

## 2. Clean the PRICE column (Cr / Lac -> rupees)

Prices come as text like `"₹45 Lac"` and `"₹4.30 Cr"`. Convert both into one numeric rupee value.

In [6]:
import re

def parse_price(p):
    if pd.isna(p):
        return np.nan
    p = p.replace("₹", "").replace(",", "").strip()
    match = re.search(r"([\d.]+)", p)
    if not match:
        return np.nan
    value = float(match.group(1))
    if "Cr" in p:
        return value * 10000000     # crore
    if "Lac" in p:
        return value * 100000       # lakh
    return value

df["price_inr"] = df["price"].apply(parse_price)
df[["price", "price_inr"]].head()

      price   price_inr
0   ₹45 Lac   4500000.0
1  ₹4.30 Cr  43000000.0
2  ₹1.11 Cr  11100000.0
3  ₹4.37 Cr  43700000.0
4  ₹1.54 Cr  15400000.0

## 3. Clean the AREA column

In [7]:
df["area_type"] = df["area"].str.extract(r"(Carpet|Super)")
df["area_sqft"] = df["area"].str.extract(r"([\d.]+)").astype(float)
df[["area", "area_type", "area_sqft"]].head()

                   area area_type  area_sqft
0   Carpet Area334 sqft    Carpet      334.0
1  Carpet Area1320 sqft    Carpet     1320.0
2   Carpet Area650 sqft    Carpet      650.0
3  Carpet Area1187 sqft    Carpet     1187.0
4   Carpet Area777 sqft    Carpet      777.0

## 4. Extract BHK from the title (now 1 to 4 BHK)

In [8]:
df["bhk"] = df["title"].str.extract(r"(\d+)\s*BHK").astype(float)
print(df["bhk"].value_counts().sort_index())

bhk
1.0    713
2.0    679
3.0    187
4.0     29
Name: count, dtype: int64

## 5. Extract and clean the LOCALITY

<div style="background:#F6ECD8; border-left:5px solid #C79A5B; padding:10px;">
The locality is pulled from the title. Many titles include a sector prefix like "Sector 35G Kharghar", so I strip the sector to get the main locality. Society names and non standard values (pincodes, "On request") are grouped as "Other".
</div>

In [9]:
# take the text after the last comma, before 'Navi Mumbai'
loc = df["title"].str.extract(r"in (.+?) Navi Mumbai")[0]
locality = loc.str.split(",").str[-1].str.strip()

# strip 'Sector NN ' prefix so 'Sector 35G Kharghar' -> 'Kharghar'
locality = locality.str.replace(r"^Sector\s+\S+\s+", "", regex=True)
# a bare 'Sector 9' with no name -> Other
locality = locality.str.replace(r"^Sector\s+\S+$", "Other", regex=True)

# real Navi Mumbai localities to keep; anything else becomes 'Other'
keep = {
    "Airoli", "Bonshet", "CBD Belapur", "Digha", "Dronagiri", "Ghansoli", "Ghot",
    "Juhu Village", "Juinagar", "Juinagar West", "Kalamboli", "Kamothe", "Karanjade",
    "Khanda Colony", "Khandeshhwar", "Khar Kopar", "Kharghar", "Kharghar Annexe",
    "Khopoli", "Kolkhe", "Kopar", "Kopar Khairane", "Koproli", "Navde", "Nerul",
    "Nerul West", "New Panvel", "New Panvel East", "Old Panvel", "Palaspa",
    "Palaspe Phata", "Palm Beach Road", "Panvel", "Panvel Road", "Roadpali",
    "Sanpada", "Seawoods", "Shedung", "Shilphata", "Shivkar", "Taloja",
    "Taloja Panchanand", "Ulwe", "Uran", "Vashi", "Rabale", "Rasayani", "Adaigaon",
    "Ajivali", "Chipale", "Rohinjan", "Pisarve", "Patalganga", "Vihighar", "Petali",
    "Shirdhon", "Chindhran", "Harigram"
}

df["locality"] = locality.apply(lambda x: x if x in keep else "Other")
print(df["locality"].value_counts().head(20))

locality
Panvel               310
Kharghar             232
Ulwe                 194
Taloja               177
New Panvel           109
Kamothe               73
Karanjade             61
Roadpali              48
Other                 43
Nerul                 38
Kopar Khairane        33
Airoli                30
Ghansoli              30
Sanpada               24
Seawoods              19
Kalamboli             19
Khopoli               16
Dronagiri             13
Vashi                 12
Taloja Panchanand     12
Name: count, dtype: int64

## 6. Strip labels from bathroom / furnishing / transaction

In [10]:
df["bathroom"] = df["bathroom"].str.replace("Bathroom", "", regex=False)
df["bathroom"] = pd.to_numeric(df["bathroom"], errors="coerce")
df["furnishing"] = df["furnishing"].str.replace("Furnishing", "", regex=False)
df["transaction"] = df["transaction"].str.replace("Transaction", "", regex=False)

print("bathroom:", sorted(df["bathroom"].dropna().unique()))
print("furnishing:", df["furnishing"].dropna().unique().tolist())
print("transaction:", df["transaction"].dropna().unique().tolist())

bathroom: [np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0)]
furnishing: ['Unfurnished', 'Semi-Furnished', 'Furnished']
transaction: ['New Property', 'Resale']

## 7. Split the FLOOR column

In [11]:
df["floor_no"] = df["floor"].str.extract(r"Floor(\d+)").astype(float)
df["total_floors"] = df["floor"].str.extract(r"out of (\d+)").astype(float)
df[["floor", "floor_no", "total_floors"]].dropna().head()

                floor  floor_no  total_floors
66  Floor22 out of 27      22.0          27.0
67  Floor33 out of 39      33.0          39.0
70  Floor10 out of 28      10.0          28.0
71   Floor4 out of 13       4.0          13.0
72   Floor6 out of 48       6.0          48.0

## 8. Split POSTED_BY into type and name

In [12]:
df["posted_by_type"] = df["posted_by"].str.split(":").str[0].str.strip()
df["posted_by_name"] = df["posted_by"].str.split(":").str[-1].str.strip()
print(df["posted_by_type"].value_counts(dropna=False))

posted_by_type
Owner      1435
NaN          90
Agent        73
Builder      10
Name: count, dtype: int64

## 9. Create PRICE PER SQFT

In [13]:
df["price_per_sqft"] = (df["price_inr"] / df["area_sqft"]).round(0)
df[["locality", "price_inr", "area_sqft", "price_per_sqft"]].head()

   locality   price_inr  area_sqft  price_per_sqft
0    Panvel   4500000.0      334.0         13473.0
1  Seawoods  43000000.0     1320.0         32576.0
2  Kharghar  11100000.0      650.0         17077.0
3     Vashi  43700000.0     1187.0         36816.0
4      Ulwe  15400000.0      777.0         19820.0

## 10. Price band

Now that the data includes 1 BHK (cheaper) and 4 BHK (pricier), the four bands still give a good spread.

In [14]:
def price_band(price):
    if price <= 5000000:          # up to 50 Lac
        return "Budget"
    elif price <= 10000000:       # 50 Lac to 1 Cr
        return "Mid"
    elif price <= 20000000:       # 1 to 2 Cr
        return "Premium"
    else:
        return "Luxury"

df["price_band"] = df["price_inr"].apply(price_band)
print(df["price_band"].value_counts())

price_band
Mid        627
Budget     549
Premium    294
Luxury     138
Name: count, dtype: int64

## 11. Handle missing values

<div style="background:#E4EDE9; border-left:5px solid #0F4C4A; padding:10px;">
The society column came back empty from the scrape, so it is dropped. Other text gaps are filled with "Unknown". Numeric gaps like floor are left as null so a fake number does not distort averages.
</div>

In [15]:
df["furnishing"] = df["furnishing"].fillna("Unknown")
df["posted_by_type"] = df["posted_by_type"].fillna("Unknown")
df["posted_by_name"] = df["posted_by_name"].fillna("Unknown")
df["area_type"] = df["area_type"].fillna("Unknown")

print(df[["furnishing", "posted_by_type", "area_type"]].isnull().sum())

furnishing        0
posted_by_type    0
area_type         0
dtype: int64

## 12. Select final columns and save

In [17]:
clean = df[[
    "locality", "bhk", "bathroom", "area_type", "area_sqft",
    "furnishing", "floor_no", "total_floors", "transaction",
    "posted_by_type", "posted_by_name",
    "price_inr", "price_per_sqft", "price_band"
]].copy()

print("final shape:", clean.shape)
clean.head(10)

final shape: (1608, 14)

,locality,bhk,bathroom,area_type,area_sqft,furnishing,floor_no,total_floors,transaction,posted_by_type,posted_by_name,price_inr,price_per_sqft,price_band
0,Panvel,1.0,1.0,Carpet,334.0,Unfurnished,NaN,NaN,New Property,Builder,Jindal Builder,4500000.0,13473.0,Budget
1,Seawoods,3.0,3.0,Carpet,1320.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,43000000.0,32576.0,Luxury
2,Kharghar,2.0,NaN,Carpet,650.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,11100000.0,17077.0,Premium
3,Vashi,3.0,3.0,Carpet,1187.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,43700000.0,36816.0,Luxury
4,Ulwe,2.0,2.0,Carpet,777.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,15400000.0,19820.0,Premium
5,Panvel,4.0,2.0,Carpet,1779.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,27300000.0,15346.0,Luxury
6,Nerul,3.0,3.0,Carpet,1250.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,38900000.0,31120.0,Luxury
7,Kharghar,4.0,3.0,Carpet,3413.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,70900000.0,20774.0,Luxury
8,Kharghar,1.0,2.0,Carpet,445.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,7510000.0,16876.0,Mid
9,Kharghar,3.0,3.0,Carpet,1094.0,Unfurnished,NaN,NaN,New Property,Unknown,Unknown,25800000.0,23583.0,Luxury

In [18]:
clean.info()
print("\nmissing values:")
print(clean.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 1608 entries, 0 to 1607
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   locality        1608 non-null   str
 1   bhk             1608 non-null   float64
 2   bathroom        1604 non-null   float64
 3   area_type       1608 non-null   str
 4   area_sqft       1608 non-null   float64
 5   furnishing      1608 non-null   str
 6   floor_no        1455 non-null   float64
 7   total_floors    1500 non-null   float64
 8   transaction     1608 non-null   str
 9   posted_by_type  1608 non-null   object
 10  posted_by_name  1608 non-null   object
 11  price_inr       1608 non-null   float64
 12  price_per_sqft  1608 non-null   float64
 13  price_band      1608 non-null   str
dtypes: float64(7), object(2), str(5)
memory usage: 233.2+ KB

missing values:
locality            0
bhk                 0
bathroom            4
area_type           0
area_sqft           0
furnishing          0
floor_no          153
total_floors      108
transaction         0
posted_by_type      0
posted_by_name      0
price_inr           0
price_per_sqft      0
price_band          0
dtype: int64

In [19]:
clean.to_csv("MagicBricks_NaviMumbai_clean.csv", index=False, encoding="utf-8-sig")
print("saved MagicBricks_NaviMumbai_clean.csv")

saved MagicBricks_NaviMumbai_clean.csv

# Reload into MySQL

In [20]:
import pandas as pd
from sqlalchemy import create_engine

clean = pd.read_csv("MagicBricks_NaviMumbai_clean.csv")
engine = create_engine("mysql+pymysql://root:1234@localhost/magicbricks")
clean.to_sql("properties_raw", engine, if_exists="replace", index=False)
print("rows loaded:", len(clean))

rows loaded: 1608